### ISSUE TITLE
Webstream is stopping after some time

### ISSUE THREAD

**Issue by jooola** [LibreTime/libretime#1453]
**Describe the bug**

We attempt to stream a remote Icecast stream through Libretime.

Everything is working as expected, but the stream stops after a random amount of time, possibly between 5 et 10 minutes.

Updating the show schedule with an extra track starts the stream again, and it will stop again after some time.

**To Reproduce**

1. Setup a web stream
2. Schedule the stream for playing
3. Listen and wait for silence

**Expected behavior**

The stream should not stop and keep stream as long as the stream duration or the show is not over.

**LibreTime version:** main branch the 2021/12/02
**Installation method:** 

- OS: Debian buster
- Method: ./install -fap

**Additional context**

```
2021/12/02 18:00:35 [server:3] New client: 127.0.0.1.
2021/12/02 18:00:35 [lang:3] dynamic_source.get_id
2021/12/02 18:00:35 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:00:35 [server:3] New client: 127.0.0.1.
2021/12/02 18:00:35 [lang:3] dynamic_source.id
2021/12/02 18:00:35 [lang:3] ["Done"]
2021/12/02 18:00:35 [lang:3] ["Done"]
2021/12/02 18:00:35 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:00:35 [server:3] New client: 127.0.0.1.
2021/12/02 18:00:35 [lang:3] streams.scheduled_play_start
2021/12/02 18:00:35 [lang:3] dynamic_source.output_start
2021/12/02 18:00:35 [lang:3] timeout --signal=KILL 45 libretime-playout-notify --media-id=2 &
2021/12/02 18:00:35 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:00:36 [lang:3] ["Done"]
2021/12/02 18:00:37 [decoder:3] Method "MAD" accepted "audio/mpeg".
2021/12/02 18:00:37 [http:3] Decoding...
2021/12/02 18:00:37 [http:3] New metadata chunk: ? -- Emission - Polemixetlavoixoff.
2021/12/02 18:00:39 [schedule_noise_switch:3] Switch to map_metadata_7793 with transition.
2021/12/02 18:00:39 [lang:3] transition called...
2021/12/02 18:00:39 [switch_7791:3] Switch to cross_7785.
2021/12/02 18:00:39 [map_metadata_7793:3] Inserting missing metadata.
2021/12/02 18:00:39 [lang:3] Using stream_format 0
2021/12/02 18:00:39 [lang:3] Using stream_format 0
2021/12/02 18:00:40 [lang:3] timeout --signal=KILL 45 libretime-playout-notify --webstream='{ "title": "Emission - Polemixetlavoixoff", "source_url": "http://radiogalere.org:8080/galere.mp3"}' --media-id=2 &
2021/12/02 18:00:40 [lang:3] URL now http://radiogalere.org:8080/galere.mp3 (change: false)
2021/12/02 18:00:40 [lang:3] Using stream_format 0

=> Something happens here

2021/12/02 18:07:15 [server:3] New client: 127.0.0.1.
2021/12/02 18:07:15 [lang:3] dynamic_source.get_id
2021/12/02 18:07:15 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:07:15 [server:3] New client: 127.0.0.1.
2021/12/02 18:07:15 [lang:3] dynamic_source.id
2021/12/02 18:07:15 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:07:15 [server:3] New client: 127.0.0.1.
2021/12/02 18:07:15 [lang:3] dynamic_source.output_stop
2021/12/02 18:07:15 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:07:15 [schedule_noise_switch:3] Switch to map_metadata_7800 with forgetful transition.
2021/12/02 18:07:15 [lang:3] transition called...
2021/12/02 18:07:15 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2021/12/02 18:07:15 [http:2] Feeding stopped: source stopped
2021/12/02 18:07:17 [cross_7785:3] No next track ready yet.
2021/12/02 18:07:17 [lang:3] URL now http://radiogalere.org:8080/galere.mp3 (change: false)
2021/12/02 18:07:17 [lang:3] New track inside HTTP stream
2021/12/02 18:07:17 [lang:3]   status: <fun>
2021/12/02 18:07:17 [lang:3]   need to cross: false
2021/12/02 18:07:17 [lang:3]   remaining 2.98353741497 sec before, 0.0 sec after
2021/12/02 18:07:20 [dummy(dot)2:3] Source failed (no more tracks) stopping output...

=> Scheduled an extra track

2021/12/02 18:12:21 [server:3] New client: 127.0.0.1.
2021/12/02 18:12:21 [lang:3] dynamic_source.get_id
2021/12/02 18:12:21 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:12:21 [server:3] New client: 127.0.0.1.
2021/12/02 18:12:21 [lang:3] dynamic_source.id
2021/12/02 18:12:21 [lang:3] ["Done"]
2021/12/02 18:12:21 [lang:3] ["Done"]
2021/12/02 18:12:21 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:12:21 [server:3] New client: 127.0.0.1.
2021/12/02 18:12:21 [lang:3] streams.scheduled_play_start
2021/12/02 18:12:21 [lang:3] dynamic_source.output_start
2021/12/02 18:12:21 [lang:3] timeout --signal=KILL 45 libretime-playout-notify --media-id=2 &
2021/12/02 18:12:21 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:12:22 [lang:3] ["Done"]
2021/12/02 18:12:24 [decoder:3] Method "MAD" accepted "audio/mpeg".
2021/12/02 18:12:24 [http:3] Decoding...
2021/12/02 18:12:24 [http:3] New metadata chunk: ? -- Emission - Polemixetlavoixoff.
2021/12/02 18:12:26 [schedule_noise_switch:3] Switch to map_metadata_7793 with transition.
2021/12/02 18:12:26 [lang:3] transition called...
2021/12/02 18:12:26 [switch_7791:3] Switch to cross_7785.
2021/12/02 18:12:26 [map_metadata_7793:3] Inserting missing metadata.
2021/12/02 18:12:26 [lang:3] Using stream_format 0
2021/12/02 18:12:26 [lang:3] Using stream_format 0
2021/12/02 18:12:26 [lang:3] timeout --signal=KILL 45 libretime-playout-notify --webstream='{ "title": "Emission - Polemixetlavoixoff", "source_url": "http://radiogalere.org:8080/galere.mp3"}' --media-id=2 &
2021/12/02 18:12:26 [lang:3] URL now http://radiogalere.org:8080/galere.mp3 (change: false)
2021/12/02 18:12:26 [lang:3] Using stream_format 0

=> Something happens here

2021/12/02 18:19:02 [server:3] New client: 127.0.0.1.
2021/12/02 18:19:02 [lang:3] dynamic_source.get_id
2021/12/02 18:19:02 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:19:02 [server:3] New client: 127.0.0.1.
2021/12/02 18:19:02 [lang:3] dynamic_source.id
2021/12/02 18:19:02 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:19:02 [server:3] New client: 127.0.0.1.
2021/12/02 18:19:02 [lang:3] dynamic_source.output_stop
2021/12/02 18:19:02 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:19:02 [http:2] Feeding stopped: source stopped
2021/12/02 18:19:02 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2021/12/02 18:19:02 [fade_in_8297:3] Warning: #get called when not #is_ready! This is normal if an operator using this source has been unused while the source has gone unavailable. If unsure about this warning, you are very welcome to report it and ask for clarifications.
2021/12/02 18:19:02 [schedule_noise_switch:3] Switch to map_metadata_7800 with forgetful transition.
2021/12/02 18:19:02 [lang:3] transition called...
2021/12/02 18:19:04 [cross_7785:3] No next track ready yet.
2021/12/02 18:19:04 [lang:3] URL now http://radiogalere.org:8080/galere.mp3 (change: false)
2021/12/02 18:19:04 [lang:3] New track inside HTTP stream
2021/12/02 18:19:04 [lang:3]   status: <fun>
2021/12/02 18:19:04 [lang:3]   need to cross: false
2021/12/02 18:19:04 [lang:3]   remaining 2.99954648526 sec before, 0.0 sec after
2021/12/02 18:19:07 [dummy(dot)2:3] Source failed (no more tracks) stopping output...

```

**Comment by jooola** [comment]
I suspect playout to flush the stream out of the play queue for some reason, and readd it on schedule update.

We need to find out what triggered the interaction between playout and liquidsoap around 18:07:15 (see logs)

**Comment by jooola** [comment]
Some extra logs with debug flag on, while the stream stops.
```
2021/12/02 18:30:19 [server:3] New client: 127.0.0.1.
2021/12/02 18:30:19 [lang:3] dynamic_source.get_id
2021/12/02 18:30:19 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:30:19 [server:3] New client: 127.0.0.1.
2021/12/02 18:30:19 [lang:3] dynamic_source.id
2021/12/02 18:30:19 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:30:19 [server:3] New client: 127.0.0.1.
2021/12/02 18:30:19 [lang:3] dynamic_source.output_stop
2021/12/02 18:30:19 [server:3] Client 127.0.0.1 disconnected.
2021/12/02 18:30:19 [cross_7785:4] Activations changed: static=[dummy(dot)2:dummy(dot)2], dynamic=[switch_7791:map_metadata_7793:dummy(dot)4:dummy(dot)4].
2021/12/02 18:30:19 [http:2] Feeding stopped: source stopped
2021/12/02 18:30:19 [schedule_noise_switch:3] Switch to map_metadata_7800 with forgetful transition.
2021/12/02 18:30:19 [add_8137:4] Activations changed: static=[], dynamic=[].
2021/12/02 18:30:19 [source:4] Source add_8137 gets down.
2021/12/02 18:30:19 [sequence_8135:4] Activations changed: static=[], dynamic=[].
2021/12/02 18:30:19 [source:4] Source sequence_8135 gets down.
2021/12/02 18:30:19 [fade_in_8134:4] Activations changed: static=[], dynamic=[].
2021/12/02 18:30:19 [source:4] Source fade_in_8134 gets down.
2021/12/02 18:30:19 [map_metadata_7793:4] Activations changed: static=[dummy(dot)4:dummy(dot)4], dynamic=[schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio].
2021/12/02 18:30:19 [fade_out_8136:4] Activations changed: static=[], dynamic=[].
2021/12/02 18:30:19 [source:4] Source fade_out_8136 gets down.
2021/12/02 18:30:19 [map_metadata_7800:4] Activations changed: static=[dummy(dot)5:dummy(dot)5], dynamic=[schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio].
2021/12/02 18:30:19 [lang:3] transition called...
2021/12/02 18:30:19 [source:4] Source add_8161 gets up.
2021/12/02 18:30:19 [add_8161:4] Content kind is {audio=2;video=0;midi=0}.
2021/12/02 18:30:19 [source:4] Source sequence_8159 gets up.
2021/12/02 18:30:19 [source:4] Source blank_8157 gets up.
2021/12/02 18:30:19 [blank_8157:4] Content kind is {audio=2;video=0;midi=0}.
2021/12/02 18:30:19 [blank_8157:4] Activations changed: static=[sequence_8159:add_8161:schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio], dynamic=[].
2021/12/02 18:30:19 [source:4] Source fade_in_8158 gets up.
2021/12/02 18:30:19 [fade_in_8158:4] Content kind is {audio=2;video=0;midi=0}.
2021/12/02 18:30:19 [source:4] Source replay_metadata_8155 gets up.
2021/12/02 18:30:19 [replay_metadata_8155:4] Content kind is {audio=2;video=0;midi=0}.
2021/12/02 18:30:19 [map_metadata_7800:4] Activations changed: static=[replay_metadata_8155:fade_in_8158:sequence_8159:add_8161:schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio, dummy(dot)5:dummy(dot)5], dynamic=[schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio].
2021/12/02 18:30:19 [replay_metadata_8155:4] Activations changed: static=[fade_in_8158:sequence_8159:add_8161:schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio], dynamic=[].
2021/12/02 18:30:19 [fade_in_8158:4] Activations changed: static=[sequence_8159:add_8161:schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio], dynamic=[].
2021/12/02 18:30:19 [sequence_8159:4] Activations changed: static=[add_8161:schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio], dynamic=[].
2021/12/02 18:30:19 [source:4] Source fade_out_8160 gets up.
2021/12/02 18:30:19 [fade_out_8160:4] Content kind is {audio=2;video=0;midi=0}.
2021/12/02 18:30:19 [source:4] Source empty_8154 gets up.
2021/12/02 18:30:19 [empty_8154:4] Content kind is {audio=2;video=0;midi=0}.
2021/12/02 18:30:19 [empty_8154:4] Activations changed: static=[fade_out_8160:add_8161:schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio], dynamic=[].
2021/12/02 18:30:19 [fade_out_8160:4] Activations changed: static=[add_8161:schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio], dynamic=[].
2021/12/02 18:30:19 [add_8161:4] Activations changed: static=[schedule_noise_switch:show_schedule_noise_switch:master_show_schedule_noise_switch:add_7867:Aïoli_Radio:Aïoli_Radio], dynamic=[].
2021/12/02 18:30:19 [blank_8157:4] Activations changed: static=[], dynamic=[].
2021/12/02 18:30:19 [source:4] Source blank_8157 gets down.
2021/12/02 18:30:19 [dummy(dot)4:3] Source failed (no more tracks) stopping output...
2021/12/02 18:30:21 [cross_7785:4] Buffering end of track...
2021/12/02 18:30:21 [http:4] End of track.
2021/12/02 18:30:21 [http:4] Buffer emptied, buffering needed.
2021/12/02 18:30:21 [cross_7785:3] No next track ready yet.
2021/12/02 18:30:21 [lang:3] URL now http://radiogalere.org:8080/galere.mp3 (change: false)
2021/12/02 18:30:21 [lang:3] New track inside HTTP stream
2021/12/02 18:30:21 [lang:3]   status: <fun>
2021/12/02 18:30:21 [lang:3]   need to cross: false
2021/12/02 18:30:21 [lang:3]   remaining 2.96755102041 sec before, 0.0 sec after
2021/12/02 18:30:21 [source:4] Source sequence_8182 gets up.
2021/12/02 18:30:21 [source:4] Source buffer_8176 gets up.
2021/12/02 18:30:21 [buffer_8176:4] Content kind is {audio=2;video=0;midi=0}.
2021/12/02 18:30:21 [buffer_8176:4] Activations changed: static=[sequence_8182:cross_7785], dynamic=[].
2021/12/02 18:30:21 [on_metadata_7784:4] Activations changed: static=[sequence_8182:cross_7785, sequence_8126:cross_7785], dynamic=[cross_7785].
2021/12/02 18:30:21 [on_metadata_7784:4] Enabling caching mode: two static activations.
2021/12/02 18:30:21 [sequence_8182:4] Activations changed: static=[cross_7785], dynamic=[].
2021/12/02 18:30:21 [sequence_8126:4] Activations changed: static=[], dynamic=[].
2021/12/02 18:30:21 [source:4] Source sequence_8126 gets down.
2021/12/02 18:30:21 [on_metadata_7784:4] Activations changed: static=[sequence_8182:cross_7785], dynamic=[cross_7785].
2021/12/02 18:30:21 [on_metadata_7784:4] Disabling caching mode.
2021/12/02 18:30:24 [buffer_8176:4] End of track.
2021/12/02 18:30:24 [buffer_8176:4] Buffer emptied, buffering needed.
2021/12/02 18:30:24 [buffer_8176:4] Activations changed: static=[], dynamic=[].
2021/12/02 18:30:24 [source:4] Source buffer_8176 gets down.
2021/12/02 18:30:24 [dummy(dot)2:3] Source failed (no more tracks) stopping output...
2021/12/02 18:30:41 [source:4] Garbage collected add_8137.
2021/12/02 18:30:41 [source:4] Garbage collected fade_out_8136.
2021/12/02 18:30:41 [source:4] Garbage collected sequence_8135.
2021/12/02 18:30:41 [source:4] Garbage collected fade_in_8134.
2021/12/02 18:30:41 [source:4] Garbage collected blank_8133.
2021/12/02 18:30:41 [source:4] Garbage collected sequence_8126.
2021/12/02 18:30:41 [source:4] Garbage collected buffer_8119.

```

**Comment by jooola** [comment]
```
2021-12-02 18:00:35,845 [pypoliqqueue] [INFO ]  waiting 6563.154862s until next scheduled item
2021-12-02 18:07:15,687 [pypofetch] [INFO ]  Queue timeout. Fetching schedule manually
```
I wonder what is the proper flow here: pypoliqqueue is waiting the right amount of time but pypofetch queue timeout forces a manual schedule fetch. Either the pypofetch should not manually fetch the new schedule because it doesn't need to ? Or the manually fetched schedule should not be empty as it currently is ?

Maybe the queue timeout should be guarded by the pypoliqqueue waiting time, and the manual schedule fetch should not be empty.

**Comment by paddatrapper** [comment]
Fixed by #1557

**Comment by boydbadten** [comment]
I just installed the latest alpha10 from git on March 5th and this problem is still happening. 

It's easy to test---just install to a clean Bionic, set up a few webstreams that are about 10 minutes long and load them into a program and listen/watch.

**Comment by jooola** [comment]
@boydbadten Some extra fixes were required. They are awaiting to be merged in #1663

**Comment by boydbadten** [comment]
Hey thanks for the update Jooola. That's why I installed a fresh one just an hour ago to check----I figured you were working on it and I need this kinda desparately---so I'm waiting-hoping.

**Comment by jooola** [comment]
@boydbadten feel free to merge the PR in your local branch, I have this running on production, and didn't face issue on my side.

**Comment by boydbadten** [comment]
jooola---thanks---I am not a programmer like you and I do not know how to "merge your PR in my local branch", the way you probably would. I only use github by following instructions. I test this sort of thing in a KVM VM in my basement by maintaining some snapshots of various linux distros in specific states and that lets me roll back to a clean state using a very fast server in order to run tests. 

But what I did in order to try your updated pypoliquidsoap.py is, as non-root:

git clone https://github.com/libretime/libretime
cd libretime
git checkout 3.0.0-alpha.10 

.....then I substituted your new pypoliquidsoap.py file into the install folder here:
/home/boyd/libretime/python_apps/pypo/pypo/pypoliquidsoap.py

....and ran the installer. The installer completes, but the playout service will not start up for me with your .py file. I was careful with how I injected your .py file in order to avoid windows carriage returns...etc. I did it two different ways with the same result. If I simply replace your .py file in the running installation here:

/usr/local/lib/python3.6/dist-packages/pypo/pypoliquidsoap.py

.....with the original from alpha-10, then the playout service (libretime-playout) does start up---and the problem with webstreams persists---either they quit after about 8 mins or else they never start up. 

I'm sorry to bother you with this litany. I am very willing to test your fix and report my results to you. But you'd have to explain to me precisely how to properly merge this
 https://github.com/libretime/libretime/blob/336714005ae6dfb75d174d2b9e7150cac0a9c09d/playout/libretime_playout/pypoliquidsoap.py
 
 into a local install source folder before installing and testing. My hacky method was evidently not helpful.

**Comment by jooola** [comment]
In that case I would recommend to wait for the alpha.11 release with the proper instructions for upgrading.
A lot of breaking changes were introduced in this release cycle and the upgrade procedure is still a draft.

If you want to invest some time in learning git, I highly recommend you read some guides online.
Basically you want to checkout the branch of my pull request.

https://stackoverflow.com/questions/5884784/how-to-pull-remote-branch-from-somebody-elses-repo

```bash
git clone https://github.com/libretime/libretime && cd libretime
git remote add jooola https://github.com/jooola/libretime
git fetch jooola
git checkout fix_webstreams
# Install
```

That said, I should stop suggesting people to fetch/test my fixes as I end up doing product support or even basic command line training and I don't want to. Please browse the internet and read the manuals for further help/instructions.
