### ISSUE TITLE
silan < 0.3.3 cueout wildly off in some cases after uploading files

### ISSUE THREAD

**Issue by leonardpg** [LibreTime/libretime#177]
Just started with LibreTime. I uploaded maybe 50 files and I've discovered at least 5 that have incorrect cueout times after upload. Sometimes up to a minute or more. I discovered it when playing back a test of a smartblock.

Is there someway to tweak the analyzer so that this does not happen? Otherwise, I was thinking of erring on the side of dead air and running a query that sets cueout = length.

Thanks!

**Comment by Robby262** [comment]
I used to see this in the good-old days when I had in incoming variable bitrate mp3. That is one reason why I pre-process incoming files with sox

**Comment by hairmare** [comment]
Analyzer uses silan to detect cue points. I think this is fixed with silan >=0.3.3. Analyzer already has some code to ignore erroneous values from silan but it's impossible for it to be perfect.

I already opened an NMU for debian https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=855319 to get it updated but it needs a new maintainer. I think you can remove silan completely to get it to not do anything but haven't tested that.

**Comment by Robbt** [comment]
If and when I have time I'm interested in helping with the maintenance of the Debian packages that are currently unmaintained, but I need to spend the time figuring out the process for doing so again.

**Comment by leonardpg** [comment]
Uploaded a bunch more last night...What seems to be happening in some cases is the cueout and length are BOTH being set to the same value.  It doesn't seem to be specific to VBR, and when I listen to the point in the song where the cueout and length are set, it's not silent. So...any ideas?

**Comment by Robby262** [comment]
Are they stereo?

**Comment by leonardpg** [comment]
Yes, stereo.
I'm getting an error when I try to build the latest version of silan from source.

What's the way, as suggested above, to just remove the cuepoint analyzer from the analyzer process?

**Comment by hairmare** [comment]
I think you can `apt-get remove silan`. I might just fail even worse though.

If building silan locally fails you might need to install some build deps. I think libavformat-dev, libavcodec-dev, libavutil-dev, libsndfile1-dev, and pkg-config should cover what's needed.

**Comment by Robby262** [comment]
I fixed this in Ubuntu Trusty here: #197

**Comment by hairmare** [comment]
If you are on Debian 7, Debian 8 or Ubuntu Xenial you can check if the NMU packages from the debian bugreport work. I built them on OBS so we can test them. Please keep in mind that these are experimental, I did not check to see if they will be upgradeable once the debian patch is merged

```
# install package signing key from obs
wget -qO- http://download.opensuse.org/repositories/home:/hairmare:/silan/Debian_7.0/Release.key \
  | apt-key add -

# add OBS repo to sources list (pick the distro you need)

# Debian Wheezy
echo 'deb http://download.opensuse.org/repositories/home:/hairmare:/silan/Debian_7.0 ./' \
  > /etc/apt/sources.list.d/hairmare_silan.list
# Debian Jessie
echo 'deb http://download.opensuse.org/repositories/home:/hairmare:/silan/Debian_8.0 ./' \
  > /etc/apt/sources.list.d/hairmare_silan.list
# Ubuntu Xenial
echo 'deb http://download.opensuse.org/repositories/home:/hairmare:/silan/xUbuntu_16.04 ./' \
  > /etc/apt/sources.list.d/hairmare_silan.list

# update local package database
apt-get update

# install silan 0.3.3 from obs packages
apt-get install silan
```

You can check that you got the nmu build with `apt-cache show silan` where the second line should display `0.3.3+nmu1` as version or by running `silan --version`. 

I couldn't get the packages built for Ubuntu Trusty. I was able to satisfy all distros build requirements except Ubuntu Trusty, the libav packages silan needs are missing from OBS. This seems to be a result of the libav/ffmpeg struggles.

The OBS packages are currently on my [home repo in OBS](https://build.opensuse.org/project/show/home:hairmare:silan), I'll get them moved to wherever we focus on with the LibreTime packages. Feel free to fork em on OBS if you would like to give building them for Trusty a crack.

**Comment by aresstokrat** [comment]
This problem still randomly appears in silan 0.3.3 , using this package from https://github.com/LibreTime/libretime/issues/214#issuecomment-305988355

**Comment by hairmare** [comment]
I added all the different ways to update silan to the [release notes](https://github.com/LibreTime/libretime/releases#issues-silan-3.0.0-alpha.2) and plan on keeping distro specific info in there until silan has been sorted everywhere. I'll add it to the main docs if I keep on copying it for a while. Hopefully we can get silan figured out before we go stable without having to keep rolling our own packages.

Since the release notes now cover how to prepare a LibreTime system with a working silan binary, I'm closing this issue. 

Please raise issues/bug reports with your distro maintainers telling them that they should update silan if your distro does not supply a working silan binary.
