### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by aresstokrat** [LibreTime/libretime#212]
Using alpha1 + debian jessie

Cannot upload mp3 file, import failed.

```
$ ls -la /srv/airtime/stor/
drwxr-xr-x 3 www-data www-data 4096 май 31 12:36 .
drwxr-xr-x 3 www-data www-data 4096 май 31 12:25 ..
drwxr-xr-x 2 www-data www-data 4096 май 31 13:07 organize
```

rights are norm.

airtime apaches conf:
```
   php_value post_max_size 500M
   php_value upload_max_filesize 500M
```

there is more than 7gb of free space.

what should i do?
Maybe its only mine problem, do you have a forum to talk about Libretime or is it ok if i'll post it here?

**Comment by Robby262** [comment]
There is an independent one here: http://web-radio-support.websitesinternational.net/

**Comment by aresstokrat** [comment]
thank you for the link, but forum there looks kinda dead.

```
[Wed May 31 12:25:32.657226 2017] [:error] [pid 19520] [client ::1:52748] PHP Warning:  parse_ini_file(/etc/airtime/production/airtime.conf): failed to open stream: No such file or directory in /usr/share/airtime/php/airtime_mvc/application/configs/conf.php on line 90, referer: http://localhost/
[Wed May 31 12:34:06.258826 2017] [mpm_prefork:notice] [pid 1052] AH00169: caught SIGTERM, shutting down
[Wed May 31 12:34:46.941532 2017] [mpm_prefork:notice] [pid 1240] AH00163: Apache/2.4.10 configured -- resuming normal operations
[Wed May 31 12:34:46.952130 2017] [core:notice] [pid 1240] AH00094: Command line: '/usr/sbin/apache2'
```

**Comment by Robby262** [comment]
It is quite new, but as you said dead - so let's wake it up? There are very few LT users ;)

**Comment by Robby262** [comment]
Your apache error says it cannot find airtime.conf
Then a clean restart. Did it work after the reboot? If not look again in the apache2 error log and plupload log, there should be more errors there.

**Comment by hairmare** [comment]
> Maybe its only mine problem, do you have a forum to talk about Libretime or is it ok if i'll post it here?

Perfectly ok, I'm not sure we have had any successful installs on Jessie so it's probably not only a problem on your box. That the `organize` directory exists indicates that the php parts where able to upload the mp3 file.

The `parse_ini_file(/etc/airtime/production/airtime.conf)` indicates that there are still left-overs from the saas branch that are misbehaving. I think the installer was adding such a link at some point/on some distros. The config reading parts really need some cleanup across the board.

You can workaround this by adding a symlink in `/etc/airtime`.

```bash
ln -s /etc/airtime /etc/airtime/production
```

I'm hoping it's only a missing symlink issue, that would explain lot's of the issues you are seeing.

**Comment by aresstokrat** [comment]
added symlink, restarted.

i did't notice same errors in apache2 error.log after reboot.

but import still failed

**Comment by hairmare** [comment]
Your analyzer log from indicates what is wrong with analyzer. It looks like it's using the wrong python magic api. This was fixed to use the one most distros provide in #169.

Can you try an install from git to check out if it works for you?

**Comment by aresstokrat** [comment]
Can you please tell me what exactly should i do? 
i never used github or git before , only downloaded archives from here.

**Comment by aresstokrat** [comment]
I did and file upload gone perfectly fine! Thank you so much! 

services still getting down, liquidsoap first but this is up to #213
